In [17]:
import numpy as np
a1=[]
r1=int(input("Enter the number of rows : "))
c1=int(input("Enter the number of columns : "))
for i in range(r1*c1):
    a1.append(float(input("Elements : ")))
a1=np.array(a1).reshape(r1,c1)
print(a1)
a2=[]
r2=int(input("Enter the number of rows : "))
c2=int(input("Enter the number of column : "))
for i in range(r2*c2):
    a2.append(float(input("Elements : ")))
a2=np.array(a2).reshape(r2,c2)
print(a2)
print("Dot product is : \n",np.dot(a1,a2))

Enter the number of rows : 2
Enter the number of columns : 3
Elements : 1
Elements : 2
Elements : 3
Elements : 4
Elements : 5
Elements : 6
[[1. 2. 3.]
 [4. 5. 6.]]
Enter the number of rows : 3
Enter the number of column : 2
Elements : 9
Elements : 8
Elements : 7
Elements : 6
Elements : 5
Elements : 4
[[9. 8.]
 [7. 6.]
 [5. 4.]]
Dot product is : 
 [[ 38.  32.]
 [101.  86.]]


In [18]:
a=[]
r=int(input("Enter the number of rows : "))
c=int(input("Enter the number of columns : "))
for i in range(r*c):
    a.append(float(input("Elements : ")))
a=np.array(a).reshape(r,c)
print("The original matrix :\n",a)
print("Transpose of the matrix :\n",a.transpose())

Enter the number of rows : 2
Enter the number of columns : 3
Elements : 1
Elements : 2
Elements : 3
Elements : 4
Elements : 5
Elements : 6
The original matrix :
 [[1. 2. 3.]
 [4. 5. 6.]]
Transpose of the matrix :
 [[1. 4.]
 [2. 5.]
 [3. 6.]]


In [20]:
a=[]
r=int(input("Enter the number of rows : "))
c=int(input("Enter the number of columns : "))
for i in range(r*c):
    a.append(float(input("Elements : ")))
a=np.array(a).reshape(r,c)
print("The original matrix :\n",a)
print("Trace of the matrix :\n",a.trace())

Enter the number of rows : 3
Enter the number of columns : 3
Elements : 1
Elements : 2
Elements : 3
Elements : 4
Elements : 5
Elements : 6
Elements : 7
Elements : 8
Elements : 9
The original matrix :
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Trace of the matrix :
 15.0


In [10]:
import numpy as np
a=[]
r=int(input("Enter the number of rows : "))
c=int(input("Enter the number of columns : "))
for i in range(r*c):
    a.append(float(input("Elements : ")))
a=np.array(a).reshape(r,c)
print("The original matrix :\n",a)
print("Rank of the matrix :\n",np.linalg.matrix_rank(a))

Enter the number of rows : 3
Enter the number of columns : 3
Elements : 1
Elements : 5
Elements : 6
Elements : 4
Elements : 2
Elements : 2
Elements : 8
Elements : 5
Elements : 2
The original matrix :
 [[1. 5. 6.]
 [4. 2. 2.]
 [8. 5. 2.]]
Rank of the matrix :
 3


In [14]:
import numpy as np
a=[]
r=int(input("Enter the number of rows : "))
for i in range(r**2):
    a.append(float(input("Elements : ")))
a=np.array(a).reshape(r,r)
print("The original matrix :\n",a)
print("Determinant of the matrix :\n",round(np.linalg.det(a)))

Enter the number of rows : 2
Elements : 4
Elements : 1
Elements : 2
Elements : 3
The original matrix :
 [[4. 1.]
 [2. 3.]]
Determinant of the matrix :
 10


In [15]:
import numpy as np
a=[]
r=int(input("Enter the number of rows : "))
for i in range(r**2):
    a.append(float(input("Elements : ")))
a=np.array(a).reshape(r,r)
print("The original matrix :\n",a)
if round(np.linalg.det(a)) !=0:
    print("Inverse :\n",np.linalg.inv(a))
else:
    print("Can not find inverse !!")

Enter the number of rows : 2
Elements : 2
Elements : 1
Elements : 2
Elements : 3
The original matrix :
 [[2. 1.]
 [2. 3.]]
Inverse :
 [[ 0.75 -0.25]
 [-0.5   0.5 ]]


In [21]:
import numpy as np
a=[]
r=int(input("Enter the number of rows : "))
c=int(input("Enter the number of columns : "))
for i in range(r*c):
    a.append(float(input("Elements : ")))
a=np.array(a).reshape(r,c)
print("The original matrix :\n",a)
va,v=np.linalg.eig(a)
print("Eigen values :\n",va)
print("Eigen matrices :\n",v)

Enter the number of rows : 2
Enter the number of columns : 2
Elements : 9
Elements : 4
Elements : 5
Elements : 2
The original matrix :
 [[9. 4.]
 [5. 2.]]
Eigen values :
 [11.17890835 -0.17890835]
Eigen matrices :
 [[ 0.87816399 -0.39949624]
 [ 0.47835971  0.91673483]]
