In [30]:
import numpy as np
a1=np.array([1,2,3,4,5])
a2=np.array([2,3,1,4,9])
print("\nThe two arrays are : ")
print("",a1,"\n",a2)
print("\nGreater than :\n")
print(np.greater(a1,a2))
print("\nGreater than or equal to :\n")
print(np.greater_equal(a1,a2))
print("\nLess than :\n")
print(np.less(a1,a2))
print("\nGreater than :\n")
print(np.less_equal(a1,a2))



The two arrays are : 
 [1 2 3 4 5] 
 [2 3 1 4 9]

Greater than :

[False False  True False False]

Greater than or equal to :

[False False  True  True False]

Less than :

[ True  True False False  True]

Greater than :

[ True  True False  True  True]


In [36]:
import numpy as np
print(np.arange(30,71,2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [42]:
import numpy as np
ar=np.array([[1,0,0],[0,1,0],[0,0,1]])
print(ar)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [43]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
v=np.arange(0,21)
print("Original vector :\n",v)
v[(v>8) & (v<16)]*=-1
print("Resultant vector :\n",v)

Original vector :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Resultant vector :
 [  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [49]:
print("matrix : \n",np.diag([1,2,3,4,5]))

matrix : 
 [[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [51]:
ar=np.array([[1,2,3],[4,1,5],[6,7,1]])
print("The array :\n",ar)
print("Sum of all elements :\n",np.sum(ar))
print("Sum of row elements :\n",np.sum(ar,axis=1))
print("Sum of column elements :\n",np.sum(ar,axis=0))

The array :
 [[1 2 3]
 [4 1 5]
 [6 7 1]]
Sum of all elements :
 30
Sum of row elements :
 [ 6 10 14]
Sum of column elements :
 [11 10  9]


In [57]:
import numpy as np
import os
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
#header = 'col1 col2 col3'
np.savetxt('array_file.txt', x, fmt="%d") 
print("After loading:")
result = np.loadtxt('array_file.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [67]:
import numpy as np
a1 = np.array([0.5,1,5])
a2 = np.array([0.49,1,0.2])
print("Original arrays:")
print(a1)
print(a2)
print("\ntwo arrays are equal (element wise) or not :")
print(a1 == a2)

Original arrays:
[0.5 1.  5. ]
[0.49 1.   0.2 ]

two arrays are equal (element wise) or not :
[False  True False]


In [84]:
a1=np.random.randint(20,size=(16)).reshape(4,4)
print("Original array :\n",a1)
a1[[0,3]]=a1[[3,0]]
print("Swapped array : \n",a1)

Original array :
 [[17 17  0 14]
 [18  3  3  4]
 [18 14  9 17]
 [ 1 17  1  0]]
Swapped array : 
 [[ 1 17  1  0]
 [18  3  3  4]
 [18 14  9 17]
 [17 17  0 14]]


In [87]:
a1=np.random.randint(10,size=(4)).reshape(2,2)
a2=np.random.randint(10,size=(4)).reshape(2,2)
print(a1,"\nx\n",a2,"\n=")
print(np.multiply(a1,a2))

[[5 4]
 [6 2]] 
x
 [[6 4]
 [4 0]] 
=
[[30 16]
 [24  0]]
